import NavBar from '@/components/NavBar';
import GlobalContext from '@/context/GlobalContext';
import { Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import type React from 'react';
import './globals.css';
import '@radix-ui/themes/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <GlobalContext>
          <Theme appearance="dark">
            <NavBar />
            {children}
          </Theme>
        </GlobalContext>
      </body>
    </html>
  );
}
